language: cpp

os: linux
sudo: required
dist: trusty

compiler:
    - gcc

addons:
    apt:
        sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - python3.5
            - python3.5-dev
            - mesa-common-dev
            - libglu1-mesa-dev

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
    - sudo apt-get -qq update
    - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh
    - sudo mkdir -p /opt/cmake

install:
    - sudo apt-get install -y qt-latest
    - sudo bash cmake-3.5.2-Linux-x86_64.sh --prefix=/opt/cmake --skip-license

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    # Qt 5.6
    - export PATH=/opt/cmake/bin:/opt/qt56/bin:$PATH
    - bash /opt/qt56/bin/qt56-env.sh
    # Build directory
    - mkdir ../build-stoiridh-settings
    - cd ../build-stoiridh-settings
    - export PATH=$HOME/viprip/build-stoiridh-settings/install-root/bin:$PATH

script:
    # CMake build
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug ../Stoiridh.Settings
    - make
    - ctest -V
